<?php

namespace App\Main;

class SideMenu
{
    /**
     * List of side menu items.
     */
    public static function menu(): array
    {
        return [
            "DASHBOARDS",
            [
                'icon' => "GaugeCircle",
                'route_name' => "dashboard-overview-1",
                'params' => [],
                'title' => "E-Commerce",
            ],
            [
                'icon' => "ActivitySquare",
                'route_name' => "dashboard-overview-2",
                'params' => [],
                'title' => "CRM",
            ],
            [
                'icon' => "Album",
                'route_name' => "dashboard-overview-3",
                'params' => [],
                'title' => "Hospital",
            ],
            [
                'icon' => "BookMarked",
                'route_name' => "dashboard-overview-4",
                'params' => [],
                'title' => "Factory",
            ],
            [
                'icon' => "HardDrive",
                'route_name' => "dashboard-overview-5",
                'params' => [],
                'title' => "Banking",
            ],
            [
                'icon' => "MousePointerSquare",
                'route_name' => "dashboard-overview-6",
                'params' => [],
                'title' => "Cafe",
            ],
            [
                'icon' => "ShieldHalf",
                'route_name' => "dashboard-overview-7",
                'params' => [],
                'title' => "Crypto",
            ],
            [
                'icon' => "Building",
                'route_name' => "dashboard-overview-8",
                'params' => [],
                'title' => "Hotel",
            ],
            "APPS",
            [
                'icon' => "GanttChartSquare",
                'route_name' => "inbox",
                'params' => [],
                'title' => "Inbox",
                'badge' => 4,
            ],
            [
                'icon' => "PanelRightInactive",
                'route_name' => "file-manager-list",
                'params' => [],
                'title' => "File Manager List",
            ],
            [
                'icon' => "PanelTopClose",
                'route_name' => "file-manager-grid",
                'params' => [],
                'title' => "File Manager Grid",
            ],
            [
                'icon' => "PanelTopInactive",
                'route_name' => "point-of-sale",
                'params' => [],
                'title' => "Point of Sale",
            ],
            [
                'icon' => "MailOpen",
                'route_name' => "chat",
                'params' => [],
                'title' => "Chat",
            ],
            [
                'icon' => "CalendarRange",
                'route_name' => "calendar",
                'params' => [],
                'title' => "Calendar",
            ],
            "UI WIDGETS",
            [
                'icon' => "Album",
                'route_name' => "creative",
                'params' => [],
                'title' => "Creative",
            ],
            [
                'icon' => "ActivitySquare",
                'route_name' => "dynamic",
                'params' => [],
                'title' => "Dynamic",
            ],
            [
                'icon' => "Keyboard",
                'route_name' => "interactive",
                'params' => [],
                'title' => "Interactive",
            ],
            "USER MANAGEMENT",
            [
                'icon' => "UserSquare",
                'route_name' => "users",
                'params' => [],
                'title' => "Users",
            ],
            [
                'icon' => "CakeSlice",
                'route_name' => "departments",
                'params' => [],
                'title' => "Departments",
            ],
            [
                'icon' => "PackagePlus",
                'route_name' => "add-user",
                'params' => [],
                'title' => "Add User",
            ],
            "PERSONAL DASHBOARD",
            [
                'icon' => "Presentation",
                'route_name' => "profile-overview",
                'params' => [],
                'title' => "Profile Overview",
            ],
            [
                'icon' => "CalendarRange",
                'route_name' => "profile-overview-events",
                'params' => [],
                'title' => "Events",
            ],
            [
                'icon' => "Medal",
                'route_name' => "profile-overview-achievements",
                'params' => [],
                'title' => "Achievements",
            ],
            [
                'icon' => "TabletSmartphone",
                'route_name' => "profile-overview-contacts",
                'params' => [],
                'title' => "Contacts",
            ],
            [
                'icon' => "Snail",
                'route_name' => "profile-overview-default",
                'params' => [],
                'title' => "Default",
            ],
            "GENERAL SETTINGS",
            [
                'icon' => "Briefcase",
                'route_name' => "settings",
                'params' => [],
                'title' => "Profile Info",
            ],
            [
                'icon' => "MailCheck",
                'route_name' => "settings-email-settings",
                'params' => [],
                'title' => "Email Settings",
            ],
            [
                'icon' => "Fingerprint",
                'route_name' => "settings-security",
                'params' => [],
                'title' => "Security",
            ],
            [
                'icon' => "Radar",
                'route_name' => "settings-preferences",
                'params' => [],
                'title' => "Preferences",
            ],
            [
                'icon' => "DoorOpen",
                'route_name' => "settings-two-factor-authentication",
                'params' => [],
                'title' => "Two-factor Authentication",
            ],
            [
                'icon' => "Keyboard",
                'route_name' => "settings-device-history",
                'params' => [],
                'title' => "Device History",
            ],
            [
                'icon' => "Ticket",
                'route_name' => "settings-notification-settings",
                'params' => [],
                'title' => "Notification Settings",
            ],
            [
                'icon' => "BusFront",
                'route_name' => "settings-connected-services",
                'params' => [],
                'title' => "Connected Services",
            ],
            [
                'icon' => "Podcast",
                'route_name' => "settings-social-media-links",
                'params' => [],
                'title' => "Social Media Links",
            ],
            [
                'icon' => "PackageX",
                'route_name' => "settings-account-deactivation",
                'params' => [],
                'title' => "Account Deactivation",
            ],
            "ACCOUNT",
            [
                'icon' => "PercentSquare",
                'route_name' => "billing",
                'params' => [],
                'title' => "Billing",
            ],
            [
                'icon' => "DatabaseZap",
                'route_name' => "invoice",
                'params' => [],
                'title' => "Invoice",
            ],
            "E-COMMERCE",
            [
                'icon' => "BookMarked",
                'route_name' => "categories",
                'params' => [],
                'title' => "Categories",
            ],
            [
                'icon' => "Compass",
                'route_name' => "add-product",
                'params' => [],
                'title' => "Add Product",
            ],
            [
                'icon' => "Table2",
                'route_name' => "products",
                'params' => [],
                'title' => "Products",
                'sub_menu' => [
                    [
                        'icon' => "LayoutPanelTop",
                        'route_name' => "product-list",
                        'params' => [],
                        'title' => "Product List",
                    ],
                    [
                        'icon' => "LayoutPanelLeft",
                        'route_name' => "product-grid",
                        'params' => [],
                        'title' => "Product Grid",
                    ],
                ],
            ],
            [
                'icon' => "SigmaSquare",
                'route_name' => "transactions",
                'params' => [],
                'title' => "Transactions",
                'sub_menu' => [
                    [
                        'icon' => "DivideSquare",
                        'route_name' => "transaction-list",
                        'params' => [],
                        'title' => "Transaction List",
                    ],
                    [
                        'icon' => "PlusSquare",
                        'route_name' => "transaction-detail",
                        'params' => [],
                        'title' => "Transaction Detail",
                    ],
                ],
            ],
            [
                'icon' => "FileArchive",
                'route_name' => "sellers",
                'params' => [],
                'title' => "Sellers",
                'sub_menu' => [
                    [
                        'icon' => "FileImage",
                        'route_name' => "seller-list",
                        'params' => [],
                        'title' => "Seller List",
                    ],
                    [
                        'icon' => "FileBox",
                        'route_name' => "seller-detail",
                        'params' => [],
                        'title' => "Seller Detail",
                    ],
                ],
            ],
            [
                'icon' => "Goal",
                'route_name' => "reviews",
                'params' => [],
                'title' => "Reviews",
            ],
            "AUTHENTICATIONS",
            [
                'icon' => "BookKey",
                'route_name' => "login",
                'params' => [],
                'title' => "Login",
            ],
            [
                'icon' => "BookLock",
                'route_name' => "register",
                'params' => [],
                'title' => "Register",
            ],
            "COMPONENTS",
            [
                'icon' => "LayoutPanelLeft",
                'title' => "Table",
                'sub_menu' => [
                    [
                        'icon' => "FlipVertical",
                        'route_name' => "regular-table",
                        'params' => [],
                        'title' => "Regular Table",
                    ],
                    [
                        'icon' => "FlipHorizontal",
                        'route_name' => "tabulator",
                        'params' => [],
                        'title' => "Tabulator",
                    ],
                ],
            ],
            [
                'icon' => "MemoryStick",
                'title' => "Overlay",
                'sub_menu' => [
                    [
                        'icon' => "MenuSquare",
                        'route_name' => "modal",
                        'params' => [],
                        'title' => "Modal",
                    ],
                    [
                        'icon' => "Newspaper",
                        'route_name' => "slideover",
                        'params' => [],
                        'title' => "Slide Over",
                    ],
                    [
                        'icon' => "PanelBottom",
                        'route_name' => "notification",
                        'params' => [],
                        'title' => "Notification",
                    ],
                ],
            ],
            [
                'icon' => "Package2",
                'route_name' => "tab",
                'params' => [],
                'title' => "Tab",
            ],
            [
                'icon' => "Pocket",
                'route_name' => "accordion",
                'params' => [],
                'title' => "Accordion",
            ],
            [
                'icon' => "PlusSquare",
                'route_name' => "button",
                'params' => [],
                'title' => "Button",
            ],
            [
                'icon' => "Presentation",
                'route_name' => "alert",
                'params' => [],
                'title' => "Alert",
            ],
            [
                'icon' => "ShieldEllipsis",
                'route_name' => "progress-bar",
                'params' => [],
                'title' => "Progress Bar",
            ],
            [
                'icon' => "Clapperboard",
                'route_name' => "tooltip",
                'params' => [],
                'title' => "Tooltip",
            ],
            [
                'icon' => "FlipVertical",
                'route_name' => "dropdown",
                'params' => [],
                'title' => "Dropdown",
            ],
            [
                'icon' => "FileType2",
                'route_name' => "typography",
                'params' => [],
                'title' => "Typography",
            ],
            [
                'icon' => "Aperture",
                'route_name' => "icon",
                'params' => [],
                'title' => "Icon",
            ],
            [
                'icon' => "Droplets",
                'route_name' => "loading-icon",
                'params' => [],
                'title' => "Loading Icon",
            ],
            [
                'icon' => "GalleryHorizontalEnd",
                'route_name' => "regular-form",
                'params' => [],
                'title' => "Regular Form",
            ],
            [
                'icon' => "Microwave",
                'route_name' => "datepicker",
                'params' => [],
                'title' => "Datepicker",
            ],
            [
                'icon' => "Disc3",
                'route_name' => "tom-select",
                'params' => [],
                'title' => "Tom Select",
            ],
            [
                'icon' => "Sandwich",
                'route_name' => "file-upload",
                'params' => [],
                'title' => "File Upload",
            ],
            [
                'icon' => "HopOff",
                'route_name' => "wysiwyg-editor",
                'params' => [],
                'title' => "Wysiwyg Editor",
            ],
            [
                'icon' => "ClipboardType",
                'route_name' => "validation",
                'params' => [],
                'title' => "Validation",
            ],
            [
                'icon' => "PieChart",
                'route_name' => "chart",
                'params' => [],
                'title' => "Chart",
            ],
            [
                'icon' => "KanbanSquare",
                'route_name' => "slider",
                'params' => [],
                'title' => "Slider",
            ],
            [
                'icon' => "Image",
                'route_name' => "image-zoom",
                'params' => [],
                'title' => "Image Zoom",
            ],
        ];
    }
}
